#!/bin/bash
# first argument is directory where to place new build
# second argumnet is path to pdb file

if [ "$#" -ne 2 ]; then
  echo "Wrong number of command line arguments"
  echo "Usage: buildnamd path/to/output path/to/pdbfile"
  exit
fi

echo "----copying setup into new location"
cp -r ~/Desktop/AD3_syt_sim/setup $1
echo "----copying pdb file into script directory"
cp $2 $1/scripts
cd $1/scripts/
echo "----running setup.sh"

ppath=$2
s1=${ppath##\/*\/} 
s2=${s1%.pdb}
sh $1/scripts/setup.sh $s2
echo "----done"
