#!/bin/bash
# first argument is directory where to place new build
# second argumnet is path to pdb file
#
# Author: Patrick Rock
# Date: July 6th, 2016
#
#

#if [ "$#" -ne 4 ]; then
#  echo "Wrong number of command line arguments"
#  echo "Usage: buildnamd path/to/output path/to/pdbfile alpha restraint_index"
#  exit
#fi

alpha=""
rest=""
out=""
pdb=""

while test $# -gt 0; do
        case "$1" in
                -a|--alpha)
                        alpha=$1
                        ;;
                -r|--restraint)
                        rest=$1
                        ;;
                -o|--out)
                        out=$1
                        ;;
                -p|--pdb)
                        pdb=$1
                        ;;
                *)
                        break
                        ;;
        esac
done

echo $out

echo "----copying setup into new location"
cp -r ~/Desktop/AD3_syt_sim/setup $out 
echo "----copying pdb file into script directory"
cp $pdb $out/scripts
cd $out/scripts/
echo "----running setup.sh"

ppath=$pdb
s1=${ppath##\/*\/} 
s2=${s1%.pdb}

######

fname=$s2"_center.pdb"
pdbname=$s2".pdb"
psfname=$s2".psf"

echo "----calculating center of mass"
~/Research/pdbtools/pdb_centermass.py -c ./$pdbname

mv $fname dys.coor

echo "----running model_setup.tcl"
vmd -dispdev text -e model_setup.tcl -args $rest # atom index to restrain

mv dys_ionized.pdb ../$pdbname
mv dys_ionized.psf ../$psfname
mv restraint.pdb ../restraint.pdb

echo "----generating namd file"
python namd.py $psfname $pdbname $s2 $alpha
mv namd.in ../namd.in

echo "----done"
